config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'users#new'
  resources :users, only: %i[new create show destroy]
  resources :groups, only: %i[index create show]
  resources :tasks, only: %i[index create general toggle done]
  get '/login' => 'users#new'
  delete '/logout' => 'users#destroy'
  get '/app/' => 'groups#index'
  get '/tasks/general' => 'tasks#general'
  get '/tasks/done' => 'tasks#done'
  patch '/tasks/:id/toggle' => 'tasks#toggle'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, length: { in: 4..64 }

  belongs_to :user
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true, length: { in: 4..16 }
  validates :description, presence: false, length: { in: 4..64 }

  belongs_to :author, class_name: 'User'
  belongs_to :group, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { in: 4..16 }

  has_many :groups
  has_many :tasks, -> { where('status = false').order(group_id: :desc) }, class_name: 'Task', foreign_key: :author_id
  has_many :done_tasks, lambda {
                          where('status = true').order(group_id: :desc)
                        }, class_name: 'Task', foreign_key: :author_id
  has_many :general_tasks, lambda {
                             where('group_id IS NULL AND status = false').order(group_id: :desc)
                           }, class_name: 'Task', foreign_key: :author_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    return nil if session[:user_id].nil?

    begin
      User.find(session[:user_id])
    rescue StandardError
      nil
    end
  end

  def user_logged_in
    if current_user
      true
    else
      redirect_to login_path
      false
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :user_logged_in, only: %i[show index]

  def index
    @user = current_user
    @groups = current_user.groups.order(name: :asc)
    @new_group = current_user.groups.build
  end

  def create
    current_user.groups.create!(group_params)
    redirect_to app_path
  end

  def show
    @group = Group.find(params[:id])
    @tasks = @group.tasks.where('status = false')
    @new_task = current_user.tasks.build
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :user_logged_in, only: %i[index create general done]

  def index
    @tasks = current_user.tasks
    @new_task = current_user.tasks.build
  end

  def general
    @tasks = current_user.general_tasks
    @new_task = current_user.tasks.build
  end

  def done
    @tasks = current_user.done_tasks
    @new_task = current_user.tasks.build
  end

  def create
    @tasks = Task.create(tasks_params)
    if @tasks.errors.any?
      flash[:error] = @tasks.errors.full_messages
    else
      @tasks.save
    end
    if params[:task][:group_id] == ''
      redirect_to tasks_path
    else
      redirect_to group_path(params[:task][:group_id])
    end
  end

  def toggle
    task = Task.find(params[:id])
    task.status = !task.status
    task.save
    redirect_to tasks_done_path
  end

  private

  def tasks_params
    param = params.require(:task).permit(:name, :description, :expiring_date, :group_id)
    param.delete(:group_id) if param[:group_id] == ''
    param[:author_id] = current_user.id
    param
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_logged_in, only: [:show]

  def new
    redirect_to app_path if current_user
    @user = User.new
  end

  def create
    @user = User.find_by_name(params[:user][:name])
    if @user.nil?
      @user = User.create(user_create)
      if @user.errors.any?
        flash[:error] = @user.errors.full_messages
        redirect_to login_path
        return
      end
    end
    session[:user_id] = @user.id
    redirect_to app_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end

  private

  def user_create
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
# rubocop:disable Layout/LineLength

module GroupsHelper
  def render_groups
    out = ''
    @groups.each do |group|
      out << "<div class=\"col-3\">
                        <a href=\"#{group_path(group.id)}\">
                            <div class=\"card w-100 h-100\">
                                <div class=\"image-setter\">
                                    <img src=\"#{group.icon}\" class=\"card-img-top\" alt=\"...\"  onerror=\"this.onerror=null;this.src='/assets/error.jpg';\">
                                </div>
                                <div class=\"card-body\">
                                    <h2><strong>#{group.name}</strong></h2>
                                    <p><strong class=\"gray\">#{group.created_at.strftime('%-d/%-m/%y - %H:%M')}</strong></p>
                                </div>
                            </div>
                        </a>
                    </div>"
    end
    out.html_safe
  end
end

# rubocop:enable Layout/LineLength

app/helpers/tasks_helper.rb
# rubocop:disable Layout/LineLength
# rubocop:disable Metrics/PerceivedComplexity
# rubocop:disable Metrics/BlockLength
# rubocop:disable Metrics/CyclomaticComplexity

module TasksHelper
  def render_tasks(title = nil)
    out = ''
    prev = 'no prev'
    flash[:error]&.each do |error|
      out << "<strong style=\"color: red\">#{error}</strong><br>"
    end
    @tasks.each do |task|
      if task.group_id != prev && !title
        prev = task.group_id
        out << "<br><strong>#{task.group ? task.group.name : 'General'}</strong>
        <hr>"
      end
      out << "<div class=\"card w-100\" style=\"max-width: 100%; margin-top: 20px\">
      <div class=\"space-between card-body\">
      <div style=\"display: flex\">
      <div class=\"icon\">
                                    <img src=\"#{task.group.nil? ? 'https://www.spaciousbreath.com/wp-content/uploads/2018/03/Giving-birth-to-Life-1080x608.jpg' : task.group.icon}\" height=\"50\" >
                                    </div>
                                <div>
                                <strong>#{task.name} - #{link_to(task.status ? 'Undone' : 'Done',
                                                                 "/tasks/#{task.id}/toggle", method: :patch)}</strong><br>
                                <strong class=\"gray\">#{task.description}</strong>
                                </div>
                                </div>
                            <div style=\"text-align: right\">
                            <strong>#{if !params[:id].nil?
                                        task.author.name
                                      else
                                        (if task.group.nil?
                                           'General task'
                                         else
                                           link_to(
                                             task.group.name, group_path(task.group_id)
                                           )
                                         end)
                                      end}</strong><br>
                          <strong class=\"gray\">#{if task.expiring_date.nil?
                                                     'Doesn\'t expires'
                                                   else
                                                     "#{task.expiring_date.strftime('%-d/%-m/%y - %H:%M')} (#{((task.expiring_date - (Time.now.in_time_zone Time.zone)).to_f / 3600).to_i} hours)"
                                                   end}</strong>
                        </div>
                        </div>
                        </div>"
    end
    out.html_safe
  end
end

# rubocop:enable Layout/LineLength
# rubocop:enable Metrics/PerceivedComplexity
# rubocop:enable Metrics/BlockLength
# rubocop:enable Metrics/CyclomaticComplexity

app/helpers/users_helper.rb
module UsersHelper
  def logout_btn
    out = "<li class=\"nav-item\">
                  #{link_to('Log out', logout_path, method: :delete, class: 'nav-link')}
              </li>".html_safe
    return out unless session[:user_id].nil?
  end

  def login_err
    out = ''
    flash[:error]&.each do |error|
      out << "<strong style=\"color: red\">#{error}</strong><br>"
    end
    out.html_safe
  end
end

app/views/groups/_modal.html.erb
<div class="modal fade" id="newGroup" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create new group</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with model: @new_group do |f| %>
            <%= f.text_field :name, placeholder: "Group name" %>
            <%= f.text_field :icon, placeholder: "Image url" %>
            <%= f.submit "Create group" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<p>Hello <%= @user.name %>,<p>
<h1>Your groups</h1>
<div class="row">
    <%= render_groups %>
    <div class="col-3">
        <a href="<%= tasks_general_path %>">
            <div class="card w-100 h-100">
                <div class="image-setter">
                    <img src="https://www.spaciousbreath.com/wp-content/uploads/2018/03/Giving-birth-to-Life-1080x608.jpg" class="card-img-top" alt="..." onerror="this.onerror=null;this.src='/assets/error.jpg';">
                </div>
                <div class="card-body">
                    <h2><strong>General tasks</strong></h2>
                </div>
            </div>
        </a>
    </div>
    <div class="col-3">
        <button type="button" class="btn w-100 h-100 p-0" data-bs-toggle="modal" data-bs-target="#newGroup">
            <div class="card w-100 h-100 center-hard p-2" style="border: 1px solid #3778c2; background-color: transparent">
            <i class="fas fa-plus-circle" style="font-size: 80px; color: #3778c2"></i>
            </div>
        </button>
    </div>
</div>
<%= render partial: "groups/modal" %>

app/views/groups/show.html.erb
<div class="image-setter" style="border-radius: 5px">
    <img src="<%= @group.icon %>" class="card-img-top" alt="..."  onerror="this.onerror=null;this.src='/assets/error.jpg';">
</div>
<div class="space-between p-1" style="margin-top: 10px;">
    <div style="display: flex; align-items: center">
        <h1 style="margin: 0; margin-right: 10px"><%= @group.name %></h1>
        <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#newTask">New task</button>
    </div>
    <h2><strong><%= @tasks.length %> tasks pending</strong></h2>
</div>
<hr>
<%= render_tasks true %>
<%= render partial: "tasks/modal" %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #3778c2">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= app_path %>"><strong>Deadline</strong></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", app_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Tasks", tasks_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "General tasks", tasks_general_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Done tasks", tasks_done_path, class: "nav-link" %>
        </li>
        </ul>
        <ul class="navbar-nav">
        <%= logout_btn %>
        </ul>
      </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManagerRor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    </head>
    
    <body>
    <%= render partial: "layouts/nav"%>
    <div class="container" style="padding: 20px 0">
    <%= yield %>
    </div>
    <div class="footer">
      Created by <a href="https://ecorniell.dev">Elbert Corniell</a>
    </div>
    <script src="https://kit.fontawesome.com/58ae6287d2.js" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/_modal.html.erb
<div class="modal fade" id="newTask" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><strong>Create new task</strong></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with model: @new_task do |f| %>
            <%= f.text_field :name, placeholder: "Task name" %>
            <%= f.text_field :group_id, placeholder: "Task name", value: params[:id], hidden: true %>
            <%= f.text_area :description, placeholder: "Task description" %>
            <%= f.datetime_field :expiring_date %>
            <%= f.submit "Create task" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/done.html.erb
<div class="space-between">
    <h1>Done tasks<h1>
    <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#newTask">New general task</button>
</div>
<%= render_tasks %>
<%= render partial: 'tasks/modal' %>

app/views/tasks/general.html.erb
<div class="space-between">
    <h1>General tasks<h1>
    <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#newTask">New general task</button>
</div>
<%= render_tasks %>
<%= render partial: 'tasks/modal' %>

app/views/tasks/index.html.erb
<div class="space-between">
    <h1>Tasks<h1>
    <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#newTask">New general task</button>
</div>
<%= render_tasks %>
<%= render partial: 'tasks/modal' %>

app/views/users/new.html.erb
<section>
    <div class="card center">
      <div class="card-body">
      <br>
      <p>Log In to</p>
          <h1><strong>Deadline</strong></h1>
          <br>
          <%= login_err %>
          <%= form_for @user do |f| %>
            <% @user.errors.full_messages.each do |error| %>
              <strong><%= error %></strong><br />
            <% end %>
            <%= f.text_field :name, placeholder: "Name" %><br />
            <br>
            <%= f.submit "Log in" %>
          <% end %>
          <br>
          <br>
          <br>
          <p>Made with simple account login. No sign up needed.<p>
      </div>
    </div>
<section>